[package]
name = "shuttle-mcp"
version = "0.1.1"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rmcp = { version = "0.1", features = ["server", "transport-io"] }
tokio = { workspace = true, features = ["full"] }
serde = { workspace = true }
reqwest = { version = "0.12", features = ["json"] }
urlencoding = "2.1"
toml = "0.8"
semver = "1.0"
