[package]
name = "shuttle-mcp"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rmcp = { version = "0.1", features = ["server", "transport-io"] }
tokio = { workspace = true, features = ["full"] }
serde = { workspace = true }
