[package]
name = "shuttle-mcp"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rmcp = { version = "0.1", features = ["server", "transport-io"] }
shuttle-api-client = { workspace = true }
shuttle-common = { workspace = true, features = ["models"] }
tokio = { workspace = true, features = ["full"] }
serde_json = { workspace = true }
schemars = "0.8"
anyhow = { workspace = true }
toml.workspace = true
dirs = { workspace = true }
serde.workspace = true
